version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - db
      - mongo
    environment:
      - RAILS_ENV=development
      - WEB_CONCURRENCY=2
      - PORT_3000=3000
      - PORT_3001=3001
    command: bundle exec puma -C config/puma.rb

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data:
