swagger: '2.0'
info:
  title: Library API
  description: API para gerenciar usuários, livros e avaliações
  version: '1.0.0'
host: localhost:3000
schemes:
  - http
paths:
  /users:
    get:
      summary: Lista todos os usuários
      responses:
        '200':
          description: Lista de usuários
  /books:
    get:
      summary: Lista todos os livros
      responses:
        '200':
          description: Lista de livros
